### ISSUE TITLE
for some reason "cuda" and "cuda-old" are broken

### ISSUE THREAD

**Issue by vince62s** [fxmarty/q4f16-gemm-gemv-benchmark#1]
they trigger exllamav2.py

```
(pt2.1.0) vincent@vince-ryzen:~/nlp/q4f16-gemm-gemv-benchmark$ python run_benchmark.py --m 1 --n 8192 --k 8192 --group_size 128 --autogptq-path ../AutoGPTQ/ --autogptq-implem cuda --act-order yes

Input: torch.Size([1, 1, 8192]), torch.float16
Linear class: /home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py
Weight: torch.Size([1024, 8192]), torch.int32
qzeros: torch.Size([64, 1024]), torch.int32
scales: torch.Size([64, 8192]), torch.float16
Traceback (most recent call last):
  File "/home/vincent/nlp/q4f16-gemm-gemv-benchmark/run_benchmark.py", line 194, in <module>
    res = linear(inp)
          ^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py", line 159, in forward
    output = ext_gemm_half_q_half(x, self.q_handle, self.outfeatures, force_cuda)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllamav2.py", line 32, in ext_gemm_half_q_half
    gemm_half_q_half(x, q_handle, output, force_cuda)
TypeError: gemm_half_q_half(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: int, arg2: torch.Tensor, arg3: bool) -> None

Invoked with: tensor([[0.2124, 0.6948, 0.7271,  ..., 0.8887, 0.0586, 0.0469]],
       device='cuda:0', dtype=torch.float16), None, tensor([[0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float16), False
```

beside this, what is the reason for triton kernels being so slow ? they usually are faster than cuda's.

**Comment by fxmarty** [comment]
Hi @vince62s thank you for giving a try. The scripts I used here are a bit old, it is possible that some bug was introduced meanwhile (AutoGPTQ now dispatches by default to exllama v2 kernel). You may need to modify them.

About the Triton kernel, I think it is just that it is not well optimized. One thing about the GPTQ with act-order kernel from exllama is that it reorders offline the weights, scales and activations and reorders on the fly the activations during inference. The triton kernel is not doing that, and rather loops over the g_idx ordering doing the compute block by block which may be very slow.

**Comment by vince62s** [comment]
right so this line needs to be changed to:
linear_class = autogptq_getclass_quantlinear(use_triton=use_triton, desc_act=act_order, disable_exllama=True, disable_exllamav2=True, group_size=args.group_size, bits=bits)

Now I get what it does.

My last point is that I don't understand why cuda-old is considered as "slow" when the speed is comparable to exllama.

**Comment by fxmarty** [comment]
I'm not sure - the implementation is different and I did not dive in deep into the differences.
